-- This file is generated by automatic tools.
library ieee;
use ieee.std_logic_1164.all;

entity l1_gate is
  port (
    op  : in  std_logic_vector(6 downto 0);
    sel:  in std_logic_vector(6 downto 0);
    z   : out std_logic
  );
end l1_gate;

architecture dataflow of l1_gate is

component mux is port(
    sel	  : in	std_logic;
    src0  :	in	std_logic;
    src1  :	in	std_logic;
    z	  : out std_logic);
end component;


component not_gate is port(   
    x   : in  std_logic;
    z   : out std_logic);
end component;

component and_gate is port(
    x: in  std_logic; 
    y: in  std_logic;
    z: out std_logic);
end component ;

signal op6_not,op5_not,op4_not,op3_not,op2_not,op1_not,op0_not, and0_out, and1_out,and2_out,and3_out,and4_out,mux6_out,mux5_out,mux4_out,mux3_out,mux2_out,mux1_out,mux0_out: std_logic;


begin
    not_6: not_gate port map(op(6),op6_not);
    not_5: not_gate port map(op(5),op5_not);
    not_4: not_gate port map(op(4),op4_not);
    not_3: not_gate port map(op(3),op3_not);
    not_2: not_gate port map(op(2),op2_not);
    not_1: not_gate port map(op(1),op1_not);
    not_0: not_gate port map(op(0),op0_not);
    
    mux2_6: mux port map(sel(6),op6_not,op(6),mux6_out);
    mux2_5: mux port map(sel(5),op5_not,op(5),mux5_out);
    mux2_4: mux port map(sel(4),op4_not,op(4),mux4_out);
    mux2_3: mux port map(sel(3),op3_not,op(3),mux3_out);
    mux2_2: mux port map(sel(2),op2_not,op(2),mux2_out);
    mux2_1: mux port map(sel(1),op1_not,op(1),mux1_out);
    mux2_0: mux port map(sel(0),op0_not,op(0),mux0_out);


    and_0: and_gate port map(mux5_out,mux4_out,and0_out);
    and_1: and_gate port map(mux3_out,mux2_out,and1_out);
    and_2: and_gate port map(mux1_out,mux0_out,and2_out);
    and_3: and_gate port map(and1_out,and0_out,and3_out);
    and_4: and_gate port map(and3_out,and2_out,and4_out);
    and_5: and_gate port map(mux6_out,and4_out,z);






end dataflow;
